name: Remote Access via VNC with Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: macos-latest

    steps:
      # تثبيت الأدوات
      - name: Install Required Tools
        run: |
          brew update
          brew install tigervnc
          brew install xquartz

      # إعداد خادم العرض الافتراضي
      - name: Start Virtual Display
        run: |
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1

      # تشغيل خادم VNC
      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1024x768 -SecurityTypes None
          echo "VNC Server is running on port 5901"

      # تثبيت Cloudflare Tunnel
      - name: Install Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-amd64.tgz -o cloudflared.tgz
          tar -xvzf cloudflared.tgz
          sudo mv cloudflared /usr/local/bin/cloudflared

      # تشغيل Cloudflare Tunnel
      - name: Start Cloudflare Tunnel
        run: |
          cloudflared tunnel --url vnc://localhost:5901 > /dev/null &
          sleep 5
          echo "Cloudflare Tunnel URL:"
          cloudflared tunnel list
          
      # إبقاء الخادم قيد التشغيل
      - name: Keep Server Running
        run: sleep 3600
