name: Debugging Workflow with Tmate

on:
  workflow_dispatch:

jobs:
  tmate-session:
    runs-on: macos-latest

    steps:
    - name: Setup Environment
      run: |
        echo "Starting debug session..."
        whoami
        uname -a

    - name: Install Tmate
      run: |
        brew install tmate || echo "Failed to install Tmate."

    - name: Start Tmate Session
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
    - name: Keep Session Alive
      run: sleep 1h
