name: Remote Access with Tmate

on:
  workflow_dispatch:

jobs:
  tmate-session:
    runs-on: macos-latest

    steps:
    - name: Install Tmate
      run: |
        brew install tmate
    - name: Start Tmate Session
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        echo "Tmate session is ready. Use the following SSH to connect:"
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
    - name: Wait for Manual Connection
      run: sleep 1h
