name: Remote Control Setup

on:
  workflow_dispatch:

jobs:
  setup-macos:
    runs-on: macos-latest

    steps:
    - name: Setup SSH Server
      run: |
        echo "Installing and starting SSH..."
        sudo systemsetup -setremotelogin on
        echo "GitHub Action running on macOS"
        whoami

    - name: Retrieve IP Address
      run: |
        echo "The public IP address is:"
        curl ifconfig.me
