name: Remote Access with Tmate

on:
  workflow_dispatch:

jobs:
  tmate-session:
    runs-on: macos-latest

    steps:
    - name: Setup Environment
      run: |
        echo "Starting debug session..."
        whoami
        uname -a

    - name: Install Tmate
      run: |
        brew update
        brew install tmate || echo "Tmate installation failed. Check Homebrew."

    - name: Start Tmate Session
      run: |
        tmate -S /tmp/tmate.sock new-session -d || echo "Failed to start Tmate session."
        tmate -S /tmp/tmate.sock wait tmate-ready || echo "Tmate session not ready."
        echo "SSH session:"
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' || echo "SSH not available."
        echo "Web session:"
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}' || echo "Web session not available."

    - name: Wait for Manual Connection
      run: sleep 3600
